apiVersion: v1
kind: Service
metadata:
  name: troubleshooting-service
  namespace: 82227493
spec:
  selector:
    app: troubleshooting
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
